New arch support
lifting-bits/remill pull request #461
Opened 2020-11-19 14:31 UTC by sschriner

2020-12-16 16:24 UTC, pgoodman approved these changes

2020-12-16 16:28 UTC, pgoodman commented
uhh I clicked approve too soon

2021-01-14 05:13 UTC, pgoodman requested changes

2021-01-14 05:13 UTC, pgoodman commented on lib/Arch/AArch32/Semantics/BINARY.cpp
> +  auto rhs = SExt<uint64_t>(Read(src2));
Normally I use `SExtTo` when specifying a destination type. In this case, you've specified `uint64_t` (an unsigned type), but the operator will convert to `int64_t` via `WST` here: https://github.com/lifting-bits/remill/blob/master/include/remill/Arch/Runtime/Operators.h#L733

I think by specifying `uint64_t` here, what's happening is a sign extension to an `int128_t`; see this: https://github.com/lifting-bits/remill/blob/master/include/remill/Arch/Runtime/Types.h#L664-L666

Is this the intention?

2021-02-06 04:47 UTC, pgoodman requested changes
Only change requested is to run `scripts/format-files` (or whatever the code formatter is called)

:-)

Don't merge this at the end of a day; we'll need to quickly follow up with changes to Anvill and Circuitous.

2021-02-10 16:34 UTC, artemdinaburg commented
Is this ready for merging :) ?

2021-02-11 00:15 UTC, pgoodman approved these changes

2021-02-12 23:28 UTC, pgoodman requested changes

2021-02-12 23:28 UTC, pgoodman commented on lib/BC/TraceLifter.cpp
> +          try_add_delay_slot(false, block);
This isn't quite right, what's needed is someting like:

```
block:
  br condition, true_block, false_block

true_block:
  lift delayed true
  call function
  br not_taken_pc

false_block:
  lift delayed false
  br not_taken_pc

```

2021-02-24 19:01 UTC, merged