Mirror Sleigh's Byte-width Flags
lifting-bits/remill pull request #668
Opened 2023-05-04 14:51 UTC by 2over12

2023-05-04 14:59 UTC, Ninja3047 commented on include/remill/Arch/AArch64/Runtime/State.h
> +#include <_types/_uint8_t.h>
don't think it's needed and it causes the linux builds to fail

2023-07-05 11:59 UTC, 2over12 commented on include/remill/Arch/AArch64/Runtime/State.h
> +  uint8_t NG;
shouldn't be required they should possibly be volatile tho

2023-07-06 14:57 UTC, Ninja3047 approved these changes

2023-07-10 13:33 UTC, Ninja3047 requested changes

2023-07-10 13:33 UTC, Ninja3047 commented on include/remill/Arch/AArch64/Runtime/State.h
>    uint64_t _3;
these should probably be volatile as well

2023-07-10 16:07 UTC, merged